### ISSUE TITLE
带有注解@TableField(exist = false)的属性会拼接到sql中

### ISSUE THREAD

**Issue by wangchong003** [yangaijun/multipleselect#1]

**Comment by yangaijun** [comment]
临时可以使用MultipleSelect.newInstance("${1}.userName, ...", new UserPO(), new UserAddressPO());
这样的方式把每个都列出来，跳过TableField(exist = false)这个字段，如果是第一张表里的，可以将第一张表放到第二个位置。  
这个TableField(exist = false)注解，马上加入

**Comment by yangaijun** [comment]
已经更新进去
