### ISSUE TITLE
当属性名与数据库字段名不一致时，sql中怎么拼接字段名而不是拼接属性名

### ISSUE THREAD

**Issue by wangchong003** [yangaijun/multipleselect#2]
// user 表
@TableId
private Integer userId
// address 表
@TableId
private Integer addressId
@TableField(value = "address_user_id")
private Integer userId

**Comment by yangaijun** [comment]
可以开启mybatis-plus的驼峰命名规则，
不过这个注解马上也可以的属性可以添加进去

**Comment by yangaijun** [comment]
此功能已经更新进去，   用的仍然是实体属性名称  
实体userName  @TableField(value = "test_user_name")
仍然是  
 "${1}.userName"            
 .like("userName" 'abcd')

**Comment by wangchong003** [comment]
select中的和where中的都可以，left join中的还是没变

**Comment by yangaijun** [comment]
恩，已经更新了
