### ISSUE TITLE
通过注解@TableId(value = "id")指定的字段名无效

### ISSUE THREAD

**Issue by wangchong003** [yangaijun/multipleselect#3]
// user 表
@TableId(value = "id")
private Integer userId

// address 表
@TableId(value = "id")
private Integer addressId
private Integer userId

测试结果：user.user_id、address.address_id

正确结果应该是user.id、address.id

**Comment by yangaijun** [comment]
可以具体一点么，是左连接还是查询的列
左连接 是  user.id == address.user_id
查询的列是 user.id as userId,   address.id addressId

**Comment by yangaijun** [comment]
可以具体一点么，是左连接还是查询的列
左连接 是 user.id = address.user_id
查询的列是 user.id as userId, address.id addressId

**Comment by yangaijun** [comment]
哦，我看到了，  这个TableId的value没有读取 ，再加个@TableField(value="id") 是可以的，这个注解等下加进去。

**Comment by yangaijun** [comment]
已经提交了
这个读取mybatis-plus的注解还不是很全面，非常感谢你的测试与提出的问题，我也会不断完善，非常感谢

**Comment by wangchong003** [comment]
大佬你太客气了，我就是先测试一遍，没太大问题就运用到实际项目中去了，这套方案实在太有效率了，我会持续关注的
