### ISSUE TITLE
括号有问题

### ISSUE THREAD

**Issue by wangchong003** [yangaijun/multipleselect#4]
multipleSelect.where("${1}")
	.division()
	.eq("userName", "张三")
	.eq("userPhone", "123")
	.or()
	.division()
	.eq("userName", "李四")
	.eq("userPhone", "456");
	
sql:	WHERE ( user_name = "张三" AND user_phone = "123" ) OR ( OR user_name = "李四" OR user_phone = "456" )

两个问题：
1.OR ( OR user_name = "李四"
多个括号的时候，第二个括号开始会多出来一个OR

我把WhereCustomSegment.java 中的第42行
if (segmentSql.get(segmentSql.size() - 1).indexOf("(") == -1 
					|| (segmentSql.get(segmentSql.size() - 1).indexOf("(") != -1 && segmentSql.get(segmentSql.size() - 1).indexOf(")") != -1))
改成if (segmentSql.get(segmentSql.size() - 1).indexOf("(") == -1)就好了

2.user_name = "李四" OR user_phone = "456"
这里我实际想要的是user_name = "李四" AND user_phone = "456"
发现
	.or()
	.division()
	.eq("userName", "李四")
	.and()
	.eq("userPhone", "456");
可以达到预期效果，但感觉怪怪的

另外，条件构造器可以再完善下吗，比如isNull、groupBy、having

**Comment by yangaijun** [comment]
括号问题已经修改;
关于or和and依然是更改后续的连接方式，不过添加了andOnce与orOnce方法用来一次使用不做后续连接方式的更改;
如：.orOnce().division().eq("userName", "李四").eq("userPhone", "456");
添加了isNull 和 isNotNull方法，关于groupBy和having  会涉及到聚集函数等，暂时没有时间完善...
