### ISSUE TITLE
orderBy最后一个逗号没去掉

### ISSUE THREAD

**Issue by wangchong003** [yangaijun/multipleselect#5]

**Comment by yangaijun** [comment]
MultipleSelect类中的setOrderBy方法中sb.append(", ");这行逗号后面多添加了个空格，我正弄着个分组的功能，暂时不好提交

**Comment by wangchong003** [comment]
等你分组弄好了再提交吧，我把sb.deleteCharAt(sb.length() - 1);改成sb.deleteCharAt(sb.length() - 2);就可以了
