### ISSUE TITLE
分页可以增加一个参数用于判断是否需要查询总条数吗

### ISSUE THREAD

**Issue by wangchong003** [yangaijun/multipleselect#6]
MultipleSelect.setPage(pageNo, pageSize, Boolean searchCount);
当searchCount为false时，不查询总条数，返回total=0

**Comment by yangaijun** [comment]
这个和sql代码没关系这个加这里不是很雅， 可以加个service 方法 只调用 mapper.mulSelect(param) 就好了

**Comment by wangchong003** [comment]
懂你的意思了
